# Generated by Django 5.0.6 on 2024-05-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=255)),
                (
                    "book_image",
                    models.ImageField(blank=True, default="fallback.png", upload_to=""),
                ),
                ("book_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name="addbook",
            name="book_image",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
